# Generated by Django 3.0.7 on 2020-06-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20200605_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='subssion_date',
            new_name='submission_date',
        ),
    ]
